# Generated by Django 4.0.6 on 2022-07-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullcard', models.CharField(db_index=True, max_length=100, verbose_name='Созданная сслыка')),
                ('CC', models.CharField(max_length=400, verbose_name='Ссылка на картинку')),
                ('FIO', models.CharField(max_length=100, verbose_name='ФИО')),
                ('date', models.CharField(max_length=5, verbose_name='Дата регистраций')),
            ],
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=100, verbose_name='Созданная сслыка')),
                ('pickter', models.CharField(max_length=400, verbose_name='Ссылка на картинку')),
                ('adreess', models.CharField(max_length=200, verbose_name='Адресс доставки')),
            ],
        ),
    ]
