# Generated by Django 4.0.3 on 2022-08-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.RemoveField(
            model_name='urls',
            name='adreess',
        ),
        migrations.RemoveField(
            model_name='urls',
            name='pickter',
        ),
        migrations.RemoveField(
            model_name='urls',
            name='url',
        ),
        migrations.AddField(
            model_name='urls',
            name='log',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='urls',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
